kind: Deployment
apiVersion: apps/v1
metadata:
  name: route-issue
  labels:
    app: route-issue
    app.kubernetes.io/component: route-issue
    app.kubernetes.io/instance: route-issue
    app.kubernetes.io/name: route-issue
    app.kubernetes.io/part-of: route-issue
    app.openshift.io/runtime: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: route-issue
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: route-issue
        deployment: route-issue
    spec:
      containers:
        - name: route-issue
          image: quay.io/openshift-examples/otq-openshift/fixme-app:202511031025
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
