
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-issue
  labels:
    app: storage-issue
    app.openshift.io/runtime: redhat
    app.kubernetes.io/part-of: storage-issue
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: storage-issue
  template:
    metadata:
      labels:
        app: storage-issue
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: storage-issue
      containers:
        - name: tools
          volumeMounts:
            - mountPath: /pvc
              name: pvc
          image: registry.access.redhat.com/ubi9/ubi-micro:latest
          command:
            - "/bin/sh"
            - "-c"
            - "sleep infinity"